import { useContext, useEffect } from "react";
import { AuthContext } from "@utils/AuthContext";
import Head from 'next/head'
import Router from "next/router";
import Footer from '@components/Footer'
import Navbar from '@components/Navbar'
import Layout from '@components/Layout';
import FullPageLoader from "@components/FullPageLoader";

export default function Client() {
  const { user, isAuthenticated, isLoading } = useContext(AuthContext);

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      Router.push('/login');
    }
  }, [isAuthenticated, isLoading]);

  if (isLoading || !isAuthenticated) {
    return <FullPageLoader />;
  }

  return (
    <>
      <Head>
        <title>Client Protected</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Layout>

        <main className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 min-h-screen">

          <section className="text-gray-600 body-font py-8">
            <h1 className="text-center font-medium text-3xl dark:text-white mb-4">Client Protected</h1>
            <h1 className="text-center font-medium text-xl dark:text-white ">If you can see this, it means you are logged in.</h1>
            <h1 className="text-center font-medium text-xl dark:text-white mb-4">
              This page did the auth checking directly on the page file.</h1>
            <h1 className="text-center font-medium dark:text-white">Username : {user?.username}</h1>
            <h1 className="text-center font-medium dark:text-white break-all">Token : {user?.token}</h1>
          </section>

        </main>

        <Footer />

      </Layout>

    </>
  )
}